"""Cambiar status de enum a string

Revision ID: 07298c010a5b
Revises: 6a017b41a3ea
Create Date: 2024-09-10 19:56:41.266018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07298c010a5b'
down_revision = '6a017b41a3ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)

    # ### end Alembic commands ###
