"""Cambio en modelo de ToDo, añado campos active y updated_at

Revision ID: 6a017b41a3ea
Revises: 99955f6835da
Create Date: 2024-09-10 14:55:58.745372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a017b41a3ea'
down_revision = '99955f6835da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('active')

    # ### end Alembic commands ###
