"""Cambio en campo de completed para usar Enum

Revision ID: 9445c785779a
Revises: 
Create Date: 2024-09-08 05:44:50.649905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9445c785779a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               type_=sa.Enum('TODO', 'IN_PROGRESS', 'DONE', name='statusenum'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=sa.Enum('TODO', 'IN_PROGRESS', 'DONE', name='statusenum'),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
