"""Cambio en campo de completed para usar Enum

Revision ID: 99955f6835da
Revises: 9445c785779a
Create Date: 2024-09-08 05:56:24.891867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99955f6835da'
down_revision = '9445c785779a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', name='statusenum'), nullable=True))
        batch_op.drop_column('completed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.VARCHAR(length=11), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
